seed: 42
device: "cpu"  # cpu or cuda

run:
  dir: logs

input:
  path: datasets
  batch_size: 100


model:
  peer_normalization: 0.03
  momentum: 0.9  # Momentum to use for the running mean in peer normalization loss.
  ff_activation: "relu_full_grad"
  bp_activation: "tanh"
  hidden_dim: 1000
  ff_num_layers: 4
  bp_num_layers: 2


training:
  epochs: 200

  learning_rate: 1e-3
  weight_decay: 3e-3
  momentum: 0.9
  scheduler: "cosine"
  downstream_learning_rate: 1e-2
  downstream_weight_decay: 3e-2

  val_idx: -1  # -1: validate only once training has finished; n: validate every n epochs.
  final_test: True  # Set to true to evaluate performance on test-set.